### ISSUE TITLE
outdir not being respected

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#10]
The command "degas.calscans(dataFileName, start=47, stop=84, refscans=[45],outdir=dataOutDir)"
puts files in current working directory no matter what outdir is set to.

**Comment by low-sky** [comment]
I have taught `gbtpipe` some respect.  This should be okay if the code uses >v0.1.0 of `gbtpipe` as required in 22308d2.

**Comment by aakepley** [comment]
I verified that this works. Cue some Aretha!
