### ISSUE TITLE
fix calibration equations

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#15]
After extensive discussions, we've arrived at the following calibration equations:

For the maps,
    1)  From the vanecal scan, we derive
                Tcal = (Tatm - Tbkg) + (Twarm - Tatm) * exp(tau*A)
                vaneCounts = mean counts in vanecal scan with vane in
    2) Calculate an OFF for each map row by averaging the first and last n scans of a row
    3) For each integration in the map, calculate
            Ta* = Tcal * [OFFrow/(vaneCounts-OFFrow)]scalar * [(ON - OFFrow)/OFFrow]vector
 
For the DCR peak scans, we don't necessarily have an off, but we can use the off track scan assuming that the sky doesn't change too much over the ~7min it takes for a peak scan.
    1)  From the vanecal scan, we derive
                Tcal = (Tatm - Tbkg) + (Twarm - Tatm) * exp(tau*A)
                vaneCounts = mean counts in vanecal scan with vane in
                skyCounts = mean counts in vanecal scan with vane out
    2) For each integration in the peak, calculate
            Ta* = Tcal * [counts/(vaneCounts-skyCounts)]
    4) Then calculate the aperture efficiency
            eta_a = 0.3516 * Ta* / Snu

I think that the calctsys routine should return Tcal, vaneCounts, and skyCounts and then the calibration is pretty straightforward.

**Comment by low-sky** [comment]
I've started this implementation.  With regards to this, I have implemented this line
```
 [OFFrow/(vaneCounts-OFFrow)]scalar
```
as
```
median(OFFrow) / (median(vaneCounts) - median(OFFrow))
```

But this could also be done as 

```
median(OFFrow / (vaneCounts - OFFrow))
```

Thoughts?  The latter seems a little more right, since it represents the spectral behaviour.  However, it will also be a lot noisier.

**Comment by aakepley** [comment]
Hmm.... Since this is an absolute scaling, I think we should be okay with 

`median(OFFrow) / (median(vaneCounts) - median(OFFrow))`

The other half of the equation takes care of the spectral shape. This is also the method that Frayer employs with his reduction routine. 

I'll flag this as a topic to bring up during the meeting.

**Comment by low-sky** [comment]
Okay, that's a good plan.  The line calibration is now implemented in [this commit](https://github.com/low-sky/degas/commit/5bc743dcc84d24af11b6c20068c04b6b0803a1d9).

Of note, instead of using a mean over the first n and last n scans of a row, instead I've fit a linear relation, skipping the middle 50% of a scan.  Since there is negligible signal in an individual scan, even if there is emission outside the middle 50%, this should work well.  However, this buffer can be adjusted with the `OffFrac` parameter in `calscans()`.

**Comment by aakepley** [comment]
Good to know.

Let me know when you'd like me to start testing all this.

**Comment by low-sky** [comment]
I've gone ahead and made the vaneCounts correction into a scalar term as suggested in 438b979
https://github.com/low-sky/degas/blob/master/degas/arguspipe.py#L249

This could use a little testing.

**Comment by low-sky** [comment]
I think we all agree we're calibrated and on the right scale now.
