### ISSUE TITLE
line in final file name?

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#16]
It would be nice if we could include the name of the line in the final map file name.

**Comment by low-sky** [comment]
The new `cleansplit` routine in the latest commit now processes the full basebands into individual lines and fits baselines on a per-cube basis.  Looks prettier.

**Comment by low-sky** [comment]
`examples/e2e.py` updated accordingly.

**Comment by aakepley** [comment]
Trying out cleansplit on NGC6946 data, I get the following error:

```
degas.cleansplit(dataOutDir+'/NGC6946.fits')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-b7de4ad8c4be> in <module>()
----> 1 degas.cleansplit(dataOutDir+'/NGC6946.fits')

/users/akepley/anaconda2/lib/python2.7/site-packages/degas/postprocess.pyc in cleansplit(filename, galaxy, Vwindow, Vgalaxy, blorder, HanningLoops)
     31                 match[index] = True
     32         MatchRow = Catalog[match]
---> 33         Galaxy = MatchRow['NAME'].data[0]
     34         print "Catalog Match with " + Galaxy
     35     V0 = MatchRow['CATVEL'].data[0] * u.km / u.s

IndexError: index 0 is out of bounds for axis 0 with size 0
```
Data and reduction in /home/scratch/akepley/gbt_hcn/degas/reduction

**Comment by low-sky** [comment]
I think that's an easy fix.  You added NGC6946 to the catalog but that change is not reflected in the software's version of the catalog.  We can make a live-and-online version of the catalog.  Or, you can just copy
`/users/erosolow/code/degas/degas/data/dense_survey.cat` into your `./degas/degas/data/` directory for now and you'll get the online version next time you pull down a copy of the code.  You'll need to reinstall as well.  

Or just run the pip install on the github url.

**Comment by aakepley** [comment]
pip install https://github.com/low-sky/degas/archive/master.zip --upgrade       
plus
conda install -f numpy
to fix the mkl error worked.

Seemed to take a while (46m), but it may be because fourier was a bit overloaded. A quick look at top seemed to indicate that it was running the CPUs a lot.

```
dataOutDir = "./"+galaxy

In [3]: degas.cleansplit(dataOutDir+'/NGC6946.fits')
Catalog Match with NGC6946
Assuming HCN/HCO+ spectral setup...
|==========================================================================================================================|  42k/ 42k (100.00%)     46m56s
|==========================================================================================================================|  42k/ 42k (100.00%)     43m49s
|==========================================================================================================================|  48k/ 48k (100.00%)        22s
```

**Comment by low-sky** [comment]
This seems to be working, so closing.
