### ISSUE TITLE
intermittent baseline ripples

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#17]
David Frayer reports that he finds that sometimes one beam of ARGUS has a large intermittent ripple on the per-integration level. To search and destroy these ripples, he subtracts baseline, smooths, and then flags things that are large rms in the smoothed spectra. Don't know if this is in the DEGAS pipeline already, but wanted to pass on the info.

**Comment by low-sky** [comment]
Sort of.  It needs to be tuned up but this is the code that attempts to catch this business:

https://github.com/low-sky/gbtpipe/blob/master/gbtpipe/Gridding.py#L468

**Comment by low-sky** [comment]
Closing as ripples seem to be addressed and the major outstanding issues are in #22
