### ISSUE TITLE
create way to clip the cube depending on the weights from the gridding

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#18]
Our cubes have pretty nasty edges currently, which isn't good for analysis. I've written up a quite kludge in casa to remove the nasty edges of the cube and resize the image using the data weights. The example is at /home/scratch/akepley/gbt_hcn/degas/reduction/crop_images.py. Note that the weight level and the final box do change with images, so this function would need to account for this.

I believe that the weight level does change because we have different per pixel integration times on our target. It might be nice to give a field size and for the clipping function to pick a weight level that gets you a field of that size. However, we could possible get by with just eyeballing the weight level and using that as an input parameter.

I'm a bit concerned by the final box that contains the image moving because for NGC2146 and NGC4321, I would have thought that they would be be centered at their coordinates in the GBT catalog file and thus should be able to use the same box. NGC6946 is a much bigger map, so I'm not worried about it's box being different.

**Comment by low-sky** [comment]
Now with new fancy algorithm in 438b979
Specifically here: 
https://github.com/low-sky/degas/blob/master/degas/postprocess.py#L82

**Comment by low-sky** [comment]
Edges trimmed and cubes prettified ( 89dcb30 )
