### ISSUE TITLE
Wrong HCN/HCOp frequency

### ISSUE THREAD

**Issue by JialLi** [low-sky/degas#20]
Hi, 

In postprocess.py, the frequencies for HCN and HCOp are not correct in line52 and line55.

Line 52: for HCN, "rest_value=89.18852 * u.GHz" should be 88.631847 GHz instead;
Line 55: for HCOp, "rest_value=88.63394 * u.GHz" should be 89.188518 GHz instead.

Jialu

**Comment by low-sky** [comment]
Good catch!  Thanks a lot.  Addressed in 8ef2ef3

**Comment by aakepley** [comment]
Andy also mentioned that one of the frequencies had a typo in it. Just wanted to check whether or not that had been taken care of.

**Comment by low-sky** [comment]
I think we're good after double checking against splatalogue.  The HCN frequency refers to the F = 2-1 hyperfine, which is the bright one.
