### ISSUE TITLE
Don't double correct for ATM.

### ISSUE THREAD

**Issue by DavidFrayer** [low-sky/degas#26]
Remove line 259 of argus pipeline since chopper calibration already puts the data on the Ta* scale, so do not need to multiply by exp(tau_o*Airmass).

Thanks,

Dave

**Comment by low-sky** [comment]
Specifically https://github.com/low-sky/degas/blob/master/degas/arguspipe.py#L259

**Comment by low-sky** [comment]
Addressed in de2dd6c

**Comment by low-sky** [comment]
Test looks good ( 89dcb30 )
