### ISSUE TITLE
final cubes should have bunit='K'

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#37]
After gridding, the final cubes should have the bunit in the header set to 'K'.

**Comment by aakepley** [comment]
Like to bump the priority of this. Right now spectral cube isn't terribly happy about the lack of units.

**Comment by low-sky** [comment]
To the spectral cube issue, header keywork and cube unit are different.  This is being lost in the baselining. The original cube has the correct units.  Working on the baseline now...

**Comment by low-sky** [comment]
Addressed in `gbtpipe` commit [c2003b5](https://github.com/low-sky/gbtpipe/commit/c2003b590b622f162edbc9515d266f71246ead5f)

**Comment by aakepley** [comment]
Thanks. Managed to get a  workaround by pulling the data out directly and doing a boolean mask, but not as elegant.
